package com.atlassian.clover.recorder;

/** Global covereage recording which was previously generated by an instrumented app */
public interface GlobalCoverageRecordingTranscript extends GlobalCoverageRecording, RecordingTranscript {
    public int get(int slotIndex);
    public long getCoverageSum();
    public int addTo(int[] coverage);
    public int getCount();

}
