package com.atlassian.clover.recorder;

/** Global covereage recording which was previously generated by an instrumented app */
public interface GlobalCoverageRecordingTranscript extends GlobalCoverageRecording, RecordingTranscript {
    int get(int slotIndex);
    long getCoverageSum();
    int addTo(int[] coverage);
    int getCount();

}
