image: maven:3.6.1

pipelines:
  default:
    - step:
        caches:
          - maven
        script:
          - echo "Preparing third party dependencies ..."
          - mvn install -f clover-core-libs/jarjar/pom.xml
          - mvn install -Pworkspace-setup -f clover-core-libs/pom.xml
          - mvn install -Pworkspace-setup -f clover-eclipse/clover-eclipse-libs/pom.xml
          - mvn install -Pworkspace-setup -f clover-idea/clover-jtreemap/pom.xml
          - mvn install -Pworkspace-setup -f clover-idea/clover-idea-libs/pom.xml
          - echo "Building modules ..."
          - mvn install -f clover-buildutil/pom.xml
          - mvn install -f clover-runtime/pom.xml
          - mvn install -f clover-core/pom.xml
          - mvn install -f groovy/pom.xml
          - mvn install -f clover-ant/pom.xml
          - mvn install -f clover-eclipse/pom.xml
          - mvn install -f clover-idea/pom.xml
