package org.openclover.core.recorder;

import org.openclover.runtime.recorder.GlobalCoverageRecording;

/** Global covereage recording which was previously generated by an instrumented app */
public interface GlobalCoverageRecordingTranscript extends GlobalCoverageRecording, RecordingTranscript {
    int get(int slotIndex);
    long getCoverageSum();
    int addTo(int[] coverage);
    int getCount();

}
