package org.openclover.core.reporters.pdf;

import org.openclover.core.reporters.DonationMessageGenerator;
import org.openclover.core.reporters.pdf.api.PdfAlign;
import org.openclover.core.reporters.pdf.api.PdfBorder;
import org.openclover.core.reporters.pdf.api.PdfCanvas;
import org.openclover.core.reporters.pdf.api.PdfFontSpec;
import org.openclover.core.reporters.pdf.api.PdfFontStyle;
import org.openclover.core.reporters.pdf.api.PdfMargins;
import org.openclover.core.reporters.pdf.api.PdfPageContext;
import org.openclover.core.reporters.pdf.api.PdfPageDecorator;
import org.openclover.core.reporters.pdf.api.PdfRect;
import org.openclover.core.reporters.pdf.api.PdfStroke;
import org.openclover.core.reporters.pdf.api.PdfTable;
import org.openclover.core.reporters.pdf.api.PdfText;
import org.openclover.core.reporters.pdf.api.PdfTextBuilder;
import org.openclover.runtime.util.Formatting;
import org_openclover_runtime.CloverVersionInfo;

import java.util.Date;

/**
 * Draws the report footer — logo, generation details, donation link and the page counter — on
 * every page.
 *
 * <p>Because decorators run once the document body is complete, the total page count is simply
 * available here; the previous implementation had to reserve a placeholder and patch it in when
 * the document was closed.
 */
public class PageFooterRenderer implements PdfPageDecorator {

    private static final double SCALED_LOGO_SIZE = 32.0;
    private static final double FOOTER_FONT_SIZE = 8.0;

    /** Gap between the logo and the text block beside it. */
    private static final double LOGO_TEXT_GAP = 2.0;

    /** Room left between the logo and the first character of the text beside it. */
    private static final double LOGO_TEXT_PADDING = 6.0;

    // the icon + "Report generated by..." / donation text block occupies this fraction of the footer width,
    // the remaining fraction is reserved for the "Page X of Y" text
    private static final double TEXT_BLOCK_WIDTH_RATIO = 0.85;

    private static final PdfFontSpec FOOTER_FONT =
            PdfFontSpec.sans(FOOTER_FONT_SIZE, PdfFontStyle.ITALIC);

    private final String timestamp;
    private final PDFColours colours;

    public PageFooterRenderer(long generatedTS, PDFColours colours) {
        this.timestamp = Formatting.formatDate(new Date(generatedTS));
        this.colours = colours;
    }

    @Override
    public void decoratePage(PdfPageContext context) {
        final PdfMargins margins = context.getMargins();
        final double footerWidth = context.getPageWidth() - margins.getLeft() - margins.getRight();
        final double textBlockWidth = footerWidth * TEXT_BLOCK_WIDTH_RATIO;

        drawLogoAndFooterLines(context, margins.getLeft(), footerWidth, textBlockWidth);
        drawTextBlock(context, margins.getLeft(), textBlockWidth);
        drawPageNumber(context, margins.getLeft(), footerWidth, textBlockWidth);
    }

    private void drawLogoAndFooterLines(PdfPageContext context, double left, double footerWidth,
                                        double textBlockWidth) {
        final PdfCanvas canvas = context.getCanvas();
        canvas.drawImage("pdf_res/logo1.png",
                new PdfRect(left, 0.0, SCALED_LOGO_SIZE, SCALED_LOGO_SIZE));

        canvas.setLineWidth(PdfStroke.THIN_BORDER_WIDTH);
        // horizontal divider above the footer
        canvas.drawLine(left, SCALED_LOGO_SIZE, left + footerWidth, SCALED_LOGO_SIZE,
                colours.COL_TABLE_BORDER);
        // vertical divider between the icon+text block and the "Page X of Y" block
        canvas.drawLine(left + textBlockWidth, 0.0, left + textBlockWidth, SCALED_LOGO_SIZE,
                colours.COL_TABLE_BORDER);
    }

    private void drawTextBlock(PdfPageContext context, double left, double textBlockWidth) {
        final PdfFontSpec linkFont =
                PdfFontSpec.sans(FOOTER_FONT_SIZE, PdfFontStyle.ITALIC, colours.COL_LINK_TEXT);
        final PdfText licText = PdfText.builder()
                .add("Report generated by ", FOOTER_FONT)
                .addLink("OpenClover v" + CloverVersionInfo.RELEASE_NUM, linkFont,
                        CloverVersionInfo.OPENCLOVER_ORG)
                .add(" (" + timestamp + ")", FOOTER_FONT)
                .add("\n", FOOTER_FONT)
                .add(DonationMessageGenerator.pickMessage(), FOOTER_FONT)
                .addLink(DonationMessageGenerator.DONATE_LABEL_PLAIN, linkFont,
                        DonationMessageGenerator.DONATE_URL)
                .build();

        final PdfTable footerTab = new PdfTable(1);
        footerTab.setTotalWidth(textBlockWidth - SCALED_LOGO_SIZE - LOGO_TEXT_PADDING);
        footerTab.getDefaultStyle()
                .setBorders(PdfBorder.NONE)
                .setPadding(2.0)
                .setPaddingLeft(LOGO_TEXT_PADDING)
                .setLeading(2.0, 0.9);
        footerTab.addCell(licText);

        context.drawTable(footerTab, left + SCALED_LOGO_SIZE + LOGO_TEXT_GAP,
                SCALED_LOGO_SIZE - LOGO_TEXT_GAP);
    }

    private void drawPageNumber(PdfPageContext context, double left, double footerWidth,
                                double textBlockWidth) {
        final PdfFontSpec font = PdfFontSpec.sans(FOOTER_FONT_SIZE);
        final String text = "Page " + context.getPageNumber() + " of " + context.getTotalPages();

        // center the "Page X of Y" text within the reserved right-hand section of the footer
        final double sectionWidth = footerWidth - textBlockWidth;
        final double baselineY = SCALED_LOGO_SIZE - FOOTER_FONT_SIZE - 2.0;

        context.getCanvas().drawText(PdfText.of(text, font),
                new PdfRect(left + textBlockWidth, baselineY, sectionWidth, FOOTER_FONT_SIZE),
                PdfAlign.Horizontal.CENTER);
    }
}
