package org.openclover.core.reporters.pdf;

import com.lowagie.text.Chunk;
import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.Image;
import com.lowagie.text.Phrase;
import com.lowagie.text.Rectangle;
import com.lowagie.text.pdf.BaseFont;
import com.lowagie.text.pdf.PdfContentByte;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfPageEventHelper;
import com.lowagie.text.pdf.PdfTemplate;
import com.lowagie.text.pdf.PdfWriter;
import org.openclover.core.reporters.DonationMessageGenerator;
import org.openclover.runtime.util.Formatting;
import org_openclover_runtime.CloverVersionInfo;

import java.io.IOException;
import java.util.Date;

public class PageFooterRenderer
        extends PdfPageEventHelper {

    // This is the contentbyte object of the writer
    private PdfContentByte cb;

    // we will put the final number of pages in a template
    private PdfTemplate footerTmpl;

    // we will put the final number of pages in a template
    private PdfTemplate totalPageTmpl;

    private BaseFont pageNumFont = null;

    private float footerWidth;
    private float textBlockWidth;

    private static final int SCALED_LOGO_SIZE = 32;
    private static final int FOOTER_FONT_SIZE = 8;

    // the icon + "Report generated by..." / donation text block occupies this fraction of the footer width,
    // the remaining fraction is reserved for the "Page X of Y" text
    private static final float TEXT_BLOCK_WIDTH_RATIO = 0.85f;

    private final String timestamp;
    private final Rectangle pgsize;
    private final PDFColours colours;

    public PageFooterRenderer(Rectangle size, long generatedTS, PDFColours colours) {
        pgsize = size;
        timestamp = Formatting.formatDate(new Date(generatedTS));
        this.colours = colours;
    }

    // we override the onOpenDocument method
    @Override
    public void onOpenDocument(PdfWriter writer, Document document) {
        try {
            pageNumFont = BaseFont.createFont(BaseFont.HELVETICA, BaseFont.CP1252, BaseFont.NOT_EMBEDDED);
            cb = writer.getDirectContent();
            footerWidth = pgsize.width() - 25 - 25; //## HACK magic - 2*page margin
            textBlockWidth = footerWidth * TEXT_BLOCK_WIDTH_RATIO;
            footerTmpl = cb.createTemplate(footerWidth, SCALED_LOGO_SIZE);
            drawLogoAndFooterLines(footerTmpl);

            Phrase licText = new Phrase("Report generated by ", FontFactory.getFont(FontFactory.HELVETICA, 8, Font.ITALIC));
            licText.add(createOpenCloverVersionChunk());
            licText.add(createTimestampChunk());
            licText.add(new Chunk("\n"));
            licText.add(createDonationText());

            PdfPTable footerTab = new PdfPTable(1);
            footerTab.setTotalWidth(textBlockWidth - SCALED_LOGO_SIZE - 6);
            footerTab.getDefaultCell().setBorder(Rectangle.NO_BORDER);
            footerTab.getDefaultCell().setPadding(2f);
            footerTab.getDefaultCell().setPaddingLeft(6f);
            footerTab.getDefaultCell().setLeading(2f, 0.9f);
            footerTab.addCell(licText);

            footerTab.writeSelectedRows(0, -1, SCALED_LOGO_SIZE + 2, SCALED_LOGO_SIZE - 2, footerTmpl);
            totalPageTmpl = cb.createTemplate(25, 25);

        } catch (DocumentException de) {
            throw new RuntimeException(de);
            //##HACK - what to do here?
            //de.printStackTrace();
        } catch (IOException ioe) {
            throw new RuntimeException(ioe);
            //##HACK - what to do here?
            //ioe.printStackTrace();
        }
    }

    private void drawLogoAndFooterLines(PdfTemplate footerTmpl) throws IOException, DocumentException {
        Image logo = Image.getInstance(getClass().getClassLoader().getResource("pdf_res/logo1.png"));
        footerTmpl.addImage(logo, SCALED_LOGO_SIZE, 0, 0, SCALED_LOGO_SIZE, 0, 0);

        // horizontal divider at the bottom
        footerTmpl.setLineWidth(0.5f);
        footerTmpl.setColorStroke(colours.COL_TABLE_BORDER);
        footerTmpl.moveTo(0, SCALED_LOGO_SIZE);
        footerTmpl.lineTo(footerWidth, SCALED_LOGO_SIZE);
        footerTmpl.stroke();

        // vertical divider between the icon+text block and the "Page X of Y" block
        footerTmpl.moveTo(textBlockWidth, 0);
        footerTmpl.lineTo(textBlockWidth, SCALED_LOGO_SIZE);
        footerTmpl.stroke();
    }

    private Phrase createTimestampChunk() {
        return new Phrase(" (" + timestamp + ")",
                FontFactory.getFont(FontFactory.HELVETICA, 8, Font.ITALIC));
    }

    private Chunk createOpenCloverVersionChunk() {
        return new Chunk("OpenClover v" + CloverVersionInfo.RELEASE_NUM,
                FontFactory.getFont(
                        FontFactory.HELVETICA, 8, Font.ITALIC,
                        colours.COL_LINK_TEXT)).setAnchor(CloverVersionInfo.OPENCLOVER_ORG);
    }

    private Phrase createDonationText() {
        Phrase donationText = new Phrase(DonationMessageGenerator.pickMessage(),
                FontFactory.getFont(FontFactory.HELVETICA, 8, Font.ITALIC));
        donationText.add(new Chunk(DonationMessageGenerator.DONATE_LABEL,
                FontFactory.getFont(
                        FontFactory.HELVETICA, 8, Font.ITALIC,
                        colours.COL_LINK_TEXT)).setAnchor(DonationMessageGenerator.DONATE_URL));
        return donationText;
    }

    // we override the onEndPage method
    @Override
    public void onEndPage(PdfWriter writer, Document document) {
        int pageN = writer.getPageNumber();
        String text = "Page " + pageN + " of ";
        float len = pageNumFont.getWidthPoint(text, FOOTER_FONT_SIZE);
        float max = pageNumFont.getWidthPoint("99", FOOTER_FONT_SIZE);
        int FROM_BOTTOM = 0;// ##HACK - test how close to the bottom to go
        // centre the "Page X of Y" text within the reserved right-hand section of the footer
        float pageNumSectionWidth = footerWidth - textBlockWidth;
        float startX = 25 + textBlockWidth + (pageNumSectionWidth - len - max) / 2;

        cb.beginText();
        cb.setFontAndSize(pageNumFont, FOOTER_FONT_SIZE);
        cb.setTextMatrix(startX, FROM_BOTTOM + SCALED_LOGO_SIZE - FOOTER_FONT_SIZE - 2);
        cb.showText(text);
        cb.endText();
        cb.addTemplate(footerTmpl, 25, FROM_BOTTOM);
        cb.addTemplate(totalPageTmpl, startX + len, FROM_BOTTOM + SCALED_LOGO_SIZE - FOOTER_FONT_SIZE - 2);
    }

    // we override the onCloseDocument method
    @Override
    public void onCloseDocument(PdfWriter writer, Document document) {
        totalPageTmpl.beginText();
        totalPageTmpl.setFontAndSize(pageNumFont, FOOTER_FONT_SIZE);
        totalPageTmpl.showText(String.valueOf(writer.getPageNumber() - 1));
        totalPageTmpl.endText();
    }

}
