package org.openclover.core.reporters.pdf;

import org.openclover.core.reporters.DonationMessageGenerator;
import org.openclover.core.reporters.pdf.api.PdfAlign;
import org.openclover.core.reporters.pdf.api.PdfBorder;
import org.openclover.core.reporters.pdf.api.PdfCanvas;
import org.openclover.core.reporters.pdf.api.PdfFontSpec;
import org.openclover.core.reporters.pdf.api.PdfFontStyle;
import org.openclover.core.reporters.pdf.api.PdfPageContext;
import org.openclover.core.reporters.pdf.api.PdfPageDecorator;
import org.openclover.core.reporters.pdf.api.PdfRect;
import org.openclover.core.reporters.pdf.api.PdfTable;
import org.openclover.core.reporters.pdf.api.PdfText;
import org.openclover.runtime.util.Formatting;
import org_openclover_runtime.CloverVersionInfo;

import java.util.Date;

/**
 * Draws the report footer — logo, generation details, donation link and the page counter — on
 * every page.
 *
 * <p>Because decorators run once the document body is complete, the total page count is simply
 * available here; the previous implementation had to reserve a placeholder and patch it in when
 * the document was closed.
 */
public class PageFooterRenderer implements PdfPageDecorator {

    private static final int SCALED_LOGO_SIZE = 32;
    private static final int FOOTER_FONT_SIZE = 8;

    /** Page margin, matching the one the document body is laid out with. */
    private static final double PAGE_MARGIN = 25;

    // the icon + "Report generated by..." / donation text block occupies this fraction of the footer width,
    // the remaining fraction is reserved for the "Page X of Y" text
    private static final double TEXT_BLOCK_WIDTH_RATIO = 0.85;

    private static final PdfFontSpec FOOTER_FONT =
            PdfFontSpec.sans(FOOTER_FONT_SIZE, PdfFontStyle.ITALIC);

    private final String timestamp;
    private final PDFColours colours;

    public PageFooterRenderer(long generatedTS, PDFColours colours) {
        this.timestamp = Formatting.formatDate(new Date(generatedTS));
        this.colours = colours;
    }

    @Override
    public void decoratePage(PdfPageContext context) {
        final double footerWidth = context.getPageWidth() - 2 * PAGE_MARGIN;
        final double textBlockWidth = footerWidth * TEXT_BLOCK_WIDTH_RATIO;

        drawLogoAndFooterLines(context, footerWidth, textBlockWidth);
        drawTextBlock(context, textBlockWidth);
        drawPageNumber(context, footerWidth, textBlockWidth);
    }

    private void drawLogoAndFooterLines(PdfPageContext context, double footerWidth, double textBlockWidth) {
        final PdfCanvas canvas = context.getCanvas();
        canvas.drawImage("pdf_res/logo1.png",
                new PdfRect(PAGE_MARGIN, 0, SCALED_LOGO_SIZE, SCALED_LOGO_SIZE));

        canvas.setLineWidth(0.5);
        // horizontal divider above the footer
        canvas.drawLine(PAGE_MARGIN, SCALED_LOGO_SIZE, PAGE_MARGIN + footerWidth, SCALED_LOGO_SIZE,
                colours.COL_TABLE_BORDER);
        // vertical divider between the icon+text block and the "Page X of Y" block
        canvas.drawLine(PAGE_MARGIN + textBlockWidth, 0, PAGE_MARGIN + textBlockWidth, SCALED_LOGO_SIZE,
                colours.COL_TABLE_BORDER);
    }

    private void drawTextBlock(PdfPageContext context, double textBlockWidth) {
        final PdfText licText = PdfText.of("Report generated by ", FOOTER_FONT);
        licText.addLink("OpenClover v" + CloverVersionInfo.RELEASE_NUM,
                PdfFontSpec.sans(FOOTER_FONT_SIZE, PdfFontStyle.ITALIC, colours.COL_LINK_TEXT),
                CloverVersionInfo.OPENCLOVER_ORG);
        licText.add(" (" + timestamp + ")", FOOTER_FONT);
        licText.add("\n", FOOTER_FONT);
        licText.add(DonationMessageGenerator.pickMessage(), FOOTER_FONT);
        licText.addLink(DonationMessageGenerator.DONATE_LABEL_PLAIN,
                PdfFontSpec.sans(FOOTER_FONT_SIZE, PdfFontStyle.ITALIC, colours.COL_LINK_TEXT),
                DonationMessageGenerator.DONATE_URL);

        final PdfTable footerTab = new PdfTable(1);
        footerTab.setTotalWidth(textBlockWidth - SCALED_LOGO_SIZE - 6);
        footerTab.getDefaultCell().setBorders(PdfBorder.NONE);
        footerTab.getDefaultCell().setPadding(2);
        footerTab.getDefaultCell().setPaddingLeft(6);
        footerTab.getDefaultCell().setLeading(2, 0.9);
        footerTab.addCell(licText);

        context.drawTable(footerTab, PAGE_MARGIN + SCALED_LOGO_SIZE + 2, SCALED_LOGO_SIZE - 2);
    }

    private void drawPageNumber(PdfPageContext context, double footerWidth, double textBlockWidth) {
        final PdfFontSpec font = PdfFontSpec.sans(FOOTER_FONT_SIZE);
        final String text = "Page " + context.getPageNumber() + " of " + context.getTotalPages();

        // centre the "Page X of Y" text within the reserved right-hand section of the footer
        final double sectionWidth = footerWidth - textBlockWidth;
        final double baselineY = SCALED_LOGO_SIZE - FOOTER_FONT_SIZE - 2;

        context.getCanvas().drawText(PdfText.of(text, font),
                new PdfRect(PAGE_MARGIN + textBlockWidth, baselineY, sectionWidth, FOOTER_FONT_SIZE),
                PdfAlign.Horizontal.CENTER);
    }
}
