package org.openclover.idea.autoupdater;

import java.util.List;

import static org.openclover.core.util.Lists.newArrayList;

public class AutoUpdateConfiguration {
    private boolean autoUpdate = true;
    private List<String> ignoredVersions = newArrayList();

    public AutoUpdateConfiguration(AutoUpdateConfiguration configuration) {
        autoUpdate = configuration.autoUpdate;
        ignoredVersions = newArrayList(configuration.ignoredVersions);
    }

    public AutoUpdateConfiguration() {
    }

    public AutoUpdateConfiguration(boolean autoUpdate) {
        this.autoUpdate = autoUpdate;
    }

    public boolean isAutoUpdate() {
        return autoUpdate;
    }

    public void setAutoUpdate(boolean autoUpdate) {
        this.autoUpdate = autoUpdate;
    }

    public List<String> getIgnoredVersions() {
        return ignoredVersions; // can't be unmodifiableCollection because it breaks IDEA deserializer. Barf.
    }

    public void setIgnoredVersions(List<String> list) {
        ignoredVersions = newArrayList(list);
    }

    public void addIgnoredVersion(String version) {
        ignoredVersions.add(version);
    }

    @SuppressWarnings("ALL") //autogenerated
    @Override
    public boolean equals(Object o) {
        if (this == o)
            return true;
        if (!(o instanceof AutoUpdateConfiguration))
            return false;

        final AutoUpdateConfiguration that = (AutoUpdateConfiguration) o;

        if (autoUpdate != that.autoUpdate)
            return false;
        if (!ignoredVersions.equals(that.ignoredVersions))
            return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = (autoUpdate ? 1 : 0);
        result = 31 * result + ignoredVersions.hashCode();
        return result;
    }
}
