package org.openclover.eclipse.core.projects.settings.source;

import java.util.Objects;

public class SourceFolderPattern {
    private final String srcPath;
    private final String includePattern;
    private final String excludePattern;
    private boolean enabled;


    public SourceFolderPattern(String srcPath, String includePattern, String excludePattern, boolean enabled) {
        this.srcPath = srcPath;
        this.includePattern = includePattern;
        this.excludePattern = excludePattern;
        this.enabled = enabled;
    }

    public SourceFolderPattern(SourceFolderPattern other) {
        this(other.srcPath, other.includePattern, other.excludePattern, other.enabled);
    }

    public String getSrcPath() {
        return srcPath;
    }

    public String getIncludePattern() {
        return includePattern;
    }

    public String getExcludePattern() {
        return excludePattern;
    }

    public boolean isEnabled() {
        return enabled;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    /* autogenerated */
    @Override
    public boolean equals(Object o) {
        if (this == o)
            return true;
        if (o == null || getClass() != o.getClass())
            return false;

        final SourceFolderPattern that = (SourceFolderPattern) o;

        if (enabled != that.enabled)
            return false;
        if (!Objects.equals(excludePattern, that.excludePattern))
            return false;
        if (!Objects.equals(includePattern, that.includePattern))
            return false;
        if (!Objects.equals(srcPath, that.srcPath))
            return false;

        return true;
    }

    /* autogenerated */
    @Override
    public int hashCode() {
        int result = srcPath != null ? srcPath.hashCode() : 0;
        result = 31 * result + (includePattern != null ? includePattern.hashCode() : 0);
        result = 31 * result + (excludePattern != null ? excludePattern.hashCode() : 0);
        result = 31 * result + (enabled ? 1 : 0);
        return result;
    }
}
