# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: A Test master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          cache: 'maven'

      - name: Cache Eclipse binaries
        id: cache-eclipse
        uses: actions/cache@v3
        with:
          path: clover-eclipse-libs/target/download
          key: ${{ runner.os }}-eclipse-${{ hashFiles('clover-eclipse-libs/pom.xml') }}

      - name: Cache IDEA binaries
        id: cache-idea
        uses: actions/cache@v3
        with:
          path: clover-idea-libs/target/download
          key: ${{ runner.os }}-idea-${{ hashFiles('clover-idea-libs/pom.xml') }}

      - name: Prepare third party libraries
        run: |
          mvn install -f clover-core-libs/jarjar/pom.xml
          mvn install -Pworkspace-setup -f clover-core-libs/pom.xml
          mvn install -Pworkspace-setup -f clover-eclipse-libs/pom.xml
          mvn install -Pworkspace-setup -f clover-jtreemap/pom.xml
          mvn install -Pworkspace-setup -f clover-idea-libs/pom.xml

      - name: Download KTreemap fork
        run: |
           git clone https://bitbucket.org/atlassian/ktreemap
           cd ktreemap
           git checkout ktreemap-1.1.0-atlassian-01           
           # an old maven-antrun-plugin does not recognize <target> tag
           sed -i -e 's@<artifactId>maven-antrun-plugin</artifactId>@<artifactId>maven-antrun-plugin</artifactId><version>3.1.0</version>@' pom.xml
           # maven dependency plugin fails because of missing eclipse artifact so copy it manually
           mkdir -p target/eclipse
           cp ../clover-eclipse-libs/target/extract/*.jar target/eclipse           
           mvn install -Dmdep.skip=true  
           cd ..

      - name: Compile and pack all modules
        run: |
          mvn install -DskipTests=true

      - name: Run tests for core, groovy, ant
        run: |
          mvn verify -pl clover-runtime,clover-core,clover-groovy,clover-ant

      - name: Run tests for eclipse and idea
        run: |
          mvn verify -pl clover-eclipse,clover-idea
