# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: B Compatibility tests

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          cache: 'maven'

      - name: Cache Eclipse binaries
        id: cache-eclipse
        uses: actions/cache@v3
        with:
          path: clover-eclipse-libs/target/download
          key: ${{ runner.os }}-eclipse-${{ hashFiles('clover-eclipse-libs/pom.xml') }}

      - name: Cache IDEA binaries
        id: cache-idea
        uses: actions/cache@v3
        with:
          path: clover-idea-libs/target/download
          key: ${{ runner.os }}-idea-${{ hashFiles('clover-idea-libs/pom.xml') }}

      - name: Prepare third party libraries
        run: |
          mvn install -f clover-core-libs/jarjar/pom.xml
          mvn install -Pworkspace-setup -f clover-core-libs/pom.xml
          mvn install -Pworkspace-setup -f clover-eclipse-libs/pom.xml
          mvn install -Pworkspace-setup -f clover-jtreemap/pom.xml
          mvn install -Pworkspace-setup -f clover-idea-libs/pom.xml

      - name: Download KTreemap fork
        run: |
          wget https://packages.atlassian.com/mvn/maven-atlassian-external/net/sf/jtreemap/ktreemap/1.1.0-atlassian-01/ktreemap-1.1.0-atlassian-01.jar
          wget https://packages.atlassian.com/mvn/maven-atlassian-external/net/sf/jtreemap/ktreemap/1.1.0-atlassian-01/ktreemap-1.1.0-atlassian-01.pom
          mvn install:install-file -Dfile=ktreemap-1.1.0-atlassian-01.jar -DpomFile=ktreemap-1.1.0-atlassian-01.pom

      - name: Compile and pack all modules
        run: |
          mvn install -DskipTests=true

      - name: Run tests for runtime, core, groovy, ant
        run: |
          mvn verify -pl clover-groovy,tests-functional -Pcompatibility
