name: C Prepare release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release version'
        required: true
        type: string
      nextReleaseVersion:
        description: 'Next version'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 8.0
          distribution: temurin

      - name: Prepare release tag
        run: |
          git config user.name "Marek Parfianowicz (github-actions)"
          git config user.email "marek.parfianowicz+github-actions@gmail.com"
          mvn --batch-mode release:prepare \
              "-DpreparationGoals=clean" \
              "-DreleaseVersion=${{ inputs.releaseVersion }}" "-DdevelopmentVersion=${{ inputs.nextReleaseVersion }}" \
              "-DtagNameFormat=openclover-@{project.version}" "-Dpassword=${{ secrets.GITHUB_TOKEN }}"
