name: C Prepare release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release version'
        required: true
        type: string
      nextReleaseVersion:
        description: 'Next version'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 8.0
          distribution: temurin

      - name: Prepare release tag
        run: |
          git config user.name "Marek Parfianowicz (github-actions)"
          git config user.email "marek.parfianowicz+github-actions@gmail.com"
          echo "Updating pom.xml files to version ${{ inputs.releaseVersion }}"
          mvn versions:set "-DnewVersion=${{ inputs.releaseVersion }}" -DgenerateBackupPoms=false
          git add .
          git commit -m "Prepare release openclover-${{ inputs.releaseVersion }}"
          git tag openclover-${{ inputs.releaseVersion }}
          echo "Updating pom.xml files to version ${{ inputs.nextReleaseVersion }}"
          mvn versions:set "-DnewVersion=${{ inputs.nextReleaseVersion }}" -DgenerateBackupPoms=false
          git add .
          git commit -m "Prepare for next development iteration"
          echo "Pushing commits and tag openclover-${{ inputs.releaseVersion }}"
          git push origin
          git push origin openclover-${{ inputs.releaseVersion }}
