name: D Release OpenClover

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release version'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'openclover-${{ inputs.releaseVersion }}'

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 8.0
          distribution: temurin
          cache: maven
          server-id: ossrh
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-password: ${{ secrets.OSSRH_PASSWORD }}
          gpg-private-key: ${{ secrets.ARTIFACT_SIGNING_GPG_KEY }}
          gpg-passphrase: ${{ secrets.ARTIFACT_SIGNING_GPG_PASSPHRASE }}

      - name: Prepare third party libraries
        run: |
          mvn install -f clover-core-libs/jarjar/pom.xml
          mvn install -Pworkspace-setup -f clover-core-libs/pom.xml
          mvn install -Pworkspace-setup -f clover-eclipse-libs/pom.xml
          mvn install -Pworkspace-setup -f clover-jtreemap/pom.xml
          mvn install -Pworkspace-setup -f clover-idea-libs/pom.xml

      - name: Download KTreemap fork
        run: |
          wget https://packages.atlassian.com/mvn/maven-atlassian-external/net/sf/jtreemap/ktreemap/1.1.0-atlassian-01/ktreemap-1.1.0-atlassian-01.jar
          wget https://packages.atlassian.com/mvn/maven-atlassian-external/net/sf/jtreemap/ktreemap/1.1.0-atlassian-01/ktreemap-1.1.0-atlassian-01.pom
          mvn install:install-file -Dfile=ktreemap-1.1.0-atlassian-01.jar -DpomFile=ktreemap-1.1.0-atlassian-01.pom

      - name: Publish a release
        run: |
          mvn --batch-mode deploy

      - name: Upload non-Maven artifacts
        run: |
          echo "TODO Uploading ant javadocs to openclover.org"
          SSH_ID=~/.ssh/id_ed25519
          echo ${{ secrets.sshKey }} > $SSH_ID
          echo "scp -i $SSH_ID -P $SSH_PORT -R clover-ant/target/apidocs $SSH_USERNAME@$OPENCLOVER_ORG_HOST:$OPENCLOVER_ORG_DOWNLOAD_PATH/javadoc/$VERSION"
          echo "ssh -i $SSH_ID -P $SSH_PORT $SSH_USERNAME@$OPENCLOVER_ORG_HOST 'rm -r $OPENCLOVER_ORG_DOWNLOAD_PATH/javadoc/latest'"
          echo "scp -i $SSH_ID -P $SSH_PORT -R clover-ant/target/apidocs $SSH_USERNAME@$OPENCLOVER_ORG_HOST:$OPENCLOVER_ORG_DOWNLOAD_PATH/javadoc/latest"
          echo "TODO Uploading IDEA jar and latestStableVersion.xml to openclover.org"
          echo "scp -i $SSH_ID -P $SSH_PORT clover-idea/target/clover-idea-$VERSION.jar $SSH_USERNAME@$OPENCLOVER_ORG_HOST:$OPENCLOVER_ORG_DOWNLOAD_PATH"
          echo "scp -i $SSH_ID -P $SSH_PORT clover-idea/target/autoupdate/latestStableVersion.xml $SSH_USERNAME@$OPENCLOVER_ORG_HOST:$OPENCLOVER_ORG_UPDATE_PATH"
          echo "TODO Uploading Eclipse zip to openclover.org"
          echo "scp -i $SSH_ID -P $SSH_PORT clover-eclipse/org.openclover.eclipse.updatesite/target/clover-eclipse-site-$VERSION.zip $SSH_USERNAME@$OPENCLOVER_ORG_HOST:$OPENCLOVER_ORG_DOWNLOAD_PATH"
          echo "ssh -i $SSH_ID -P $SSH_PORT $SSH_USERNAME@$OPENCLOVER_ORG_HOST 'unzip $OPENCLOVER_ORG_DOWNLOAD_PATH/clover-eclipse-site-$VERSION.zip -d $OPENCLOVER_ORG_UPDATE_PATH'"
        env:
          SSH_PORT: ${{ secrets.sshPort }}
          SSH_USERNAME: ${{ secrets.sshUsername }}
          OPENCLOVER_ORG_HOST: ${{ secrets.sshHost }}
          OPENCLOVER_ORG_DOWNLOAD_PATH: /domains/openclover.org/public_html/download/openclover
          OPENCLOVER_ORG_UPDATE_PATH: /domains/openclover.org/public_html/update
          OPENCLOVER_ORG_DOC_PATH: /domains/openclover.org/public_html/doc
          VERSION: ${{ inputs.releaseVersion }}
