name: D Release OpenClover

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release version'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'openclover-${{ inputs.releaseVersion }}'

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 1.8
          cache: maven
          server-id: ossrh
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-password: ${{ secrets.OSSRH_PASSWORD }}

      - name: Prepare third party libraries
        run: |
          mvn install -f clover-core-libs/jarjar/pom.xml
          mvn install -Pworkspace-setup -f clover-core-libs/pom.xml
          mvn install -Pworkspace-setup -f clover-eclipse-libs/pom.xml
          mvn install -Pworkspace-setup -f clover-jtreemap/pom.xml
          mvn install -Pworkspace-setup -f clover-idea-libs/pom.xml

      - name: Download KTreemap fork
        run: |
          wget https://packages.atlassian.com/mvn/maven-atlassian-external/net/sf/jtreemap/ktreemap/1.1.0-atlassian-01/ktreemap-1.1.0-atlassian-01.jar
          wget https://packages.atlassian.com/mvn/maven-atlassian-external/net/sf/jtreemap/ktreemap/1.1.0-atlassian-01/ktreemap-1.1.0-atlassian-01.pom
          mvn install:install-file -Dfile=ktreemap-1.1.0-atlassian-01.jar -DpomFile=ktreemap-1.1.0-atlassian-01.pom

      - name: Publish a release
        run: |
          mvn --batch-mode deploy -DdryRun=true -X

      - name: Upload non-Maven artifacts
        run: |
          echo "TODO Uploading ant javadocs to openclover.org"
          SSH_ID=~/.ssh/id_ed25519
          echo $SSH_KEY > $SSH_ID
          echo "scp -i $SSH_ID -P $SSH_PORT -R clover-ant/target/apidocs $OPENCLOVER_ORG_SCP/$OPENCLOVER_ORG_DOWNLOAD_PATH/javadoc/$VERSION
          
          echo "TODO Uploading IDEA jar and latestStableVersion.xml to openclover.org"
          echo "scp -i $SSH_ID -P $SSH_PORT clover-idea/target/clover-idea-$VERSION.jar $OPENCLOVER_ORG_SCP/$OPENCLOVER_ORG_DOWNLOAD_PATH"
          echo "scp -i $SSH_ID -P $SSH_PORT clover-idea/target/autoupdate/latestStableVersion.xml $OPENCLOVER_ORG_SCP/$OPENCLOVER_ORG_UPDATE_PATH"
          
          echo "TODO Uploading Eclipse zip to openclover.org"
          echo "scp -i $SSH_ID -P $SSH_PORT clover-eclipse/org.openclover.eclipse.updatesite/target/clover-eclipse-site-$VERSION.zip $OPENCLOVER_ORG_SCP/$OPENCLOVER_ORG_DOWNLOAD_PATH"
          echo "ssh -i $SSH_ID -P $SSH_PORT 'unzip $OPENCLOVER_ORG_DOWNLOAD_PATH/clover-eclipse-site-$VERSION.zip -d $OPENCLOVER_ORG_UPDATE_PATH'"

        env:
          SSH_HOST=${{ secrets.sshHost }}
          SSH_PORT=${{ secrets.sshPort }}
          SSH_USERNAME=${{ secrets.sshUsername }}
          SSH_KEY=${{ secrets.sshKey }} 
          OPENCLOVER_ORG_DOWNLOAD_PATH=/download/openclover
          OPENCLOVER_ORG_UPDATE_PATH=/update
          OPENCLOVER_ORG_DOC_PATH=/doc
          VERSION=${{ inputs.releaseVersion }}
